### ISSUE TITLE
[RRFC] Deprecated packages: automatically display dependents, to ease notifying maintainers

### ISSUE THREAD

**Issue by dandv** [npm/rfcs#155]
## Motivation ("The Why")
Very often when users install a package, they see warnings about deprecated dependencies, and don't know what to do about them.

### Example
Here are some examples from StackOverflow of user confused by this:

* [NPM warn message about deprecated package](https://stackoverflow.com/questions/35236735/npm-warn-message-about-deprecated-package)
* [npm deprecated warnings – do I need to update something?](https://stackoverflow.com/questions/34840153/npm-deprecated-warnings-do-i-need-to-update-something)
* [How to deal with deprecation warnings from npm](https://stackoverflow.com/questions/38889519/how-to-deal-with-deprecation-warnings-from-npm)
* [npm install and deprecated warnings](https://stackoverflow.com/questions/40132400/npm-install-and-deprecated-warnings)
* [Getting npm WARN deprecated](https://stackoverflow.com/questions/58989617/getting-npm-warn-deprecated)

#### Current Behaviour
![image](https://user-images.githubusercontent.com/33569/83298948-2fff6380-a1aa-11ea-917e-d12f3ce69a9f.png)

#### Desired Behaviour
npm could automatically integrate the output of `npm ls <deprecated-package`:

```
$ npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
└─┬ @material-ui/core@4.10.0
  └── popper.js@1.16.1 
```

**Comment by isaacs** [comment]
This is a good idea, but I wonder if it even needs an RFC.  I'd be fine just doing this in npm v7.  The only downside I could imagine is that it might get a bit noisy if you have a popular module that's deprecated, or a bunch of deprecated modules under a single top level dep.

There's definitely a need for us to rethink a lot of the design of our various warning outputs, this would be a good candidate for consideration there.

**Comment by dandv** [comment]
I'd be happy to see that in v7 as well. Should I file the issue somewhere else (it can also be moved to a different GitHub repo by an org owner, but no problem to file it again in the cli repo for instance).

As for popular deprecations, the noise should incentivize solutions :)

**Comment by ruyadorno** [comment]
I think this idea goes really well with the new `npm explain` command! Let me put it in the agenda so that we can get it back in our radar for post-v7.0.0.

**Comment by ruyadorno** [comment]
Action item from the [OpenRFC call](https://www.youtube.com/watch?v=MexcBT5vp14):
- Follow up RFC/PR that adds a post-install notification (similar to audit and fund) that aggregates the number of deprecated packages and surfaces that info to the user while also removes all the current warnings during install time, user then could optionally run a subcommand such as `npm explain deprecation` in order to get the detailed info.

**Comment by ruyadorno** [comment]
Thanks for bringing up this idea @dandv! Feel free to follow up with the [proper RFC](https://github.com/npm/rfcs#how-do-i-create-an-rfc) if you're interested in champion this change 😊 otherwise it will just have to wait a little longer until someone from the team has the bandwith to pick it up but after the discussion in the call it def sounds like an area we want to improve in the cli. Thanks again for your contribution 😄

**Comment by darcyclarke** [comment]
@dandv @ruyadorno Just to quickly follow up, I think `npm explain deprecation` should actually be `npm explain --deprecation` (since `explain` currently expects the second arg to be a spec). Thinking about it a bit as well, it may make sense that the same flag is supported by `npm ls` 🤔. Either way, an example of how this could work/look:

```bash
$ npm install express@2
```
```bash
added 6 packages, and audited 6 packages in 870ms

3 deprecated packages found

To find out more, run:
  npm explain --deprecated 

4 vulnerabilities found (1 low, 1 moderate, 2 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details
```

```

**Comment by ruyadorno** [comment]
Let's continue the conversation over here: https://github.com/npm/rfcs/pull/516
