### ISSUE TITLE
[RRFC] Optional files key in package-lock.json to specify the files to include in node_modules on specified package

### ISSUE THREAD

**Issue by Rafi993** [npm/rfcs#264]
## Motivation 
When you install a package from npm it will contain the full source, different type of builds and other files like README.md.
While this is not a problem most of the time. In very large projects this results in very large node_modules size.

To solve this issue this proposal introduces a optional  **files** key in package-lock.json (for each dependency in the project) this could be used to say which files to move from **staging** folder to node_modules when installing a package thus resulting in a smaller package without drastic changes to the way npm works.

### Example
For example when you are installing **react** node_modules will contain lots of files but you might end up using only **umd/react.production.min.js** file alone while the rest of the file in node_modules are not used. For advanced users of react who know what files they are using they could install react by doing

```
 npm i react -files umd/react.production.min.js
```

which will add **files** key to react in package-lock.json containing value umd/react.production.min.js and the node_modules will contain only that file. React package could do the same for their dependency reducing the file size.  

#### Current Behaviour
Right now when you do `npm install react` the following happens
1. Compressed React package is downloaded from npm registery (or other place you have specified)
2. It is extracted to .staging folder
3. The all its dependency gets downloaded recursively to staging folder
4. On completion the contents of staging folder is copied to the respective folders in node_modules

#### Desired Behaviour
When you do `npm install react -files umd/react.production.min.js ` the following should happens
1. Compressed React package is downloaded from npm registery (or other place you have specified)
2. It is extracted to .staging folder
3. All the dependency of react gets downloaded recursively
4. files key gets added to package-lock.json to the react package with entry **umd/react.production.min.js**
4. On completion if the files key is present in package-lock.json for the specified package only that file gets copied to **node_modules** for the specified package
5. If the files key is not present all the contents of that package are copied to **node_modules**
 
### References
* n/a

**Comment by Rafi993** [comment]
Even if user deletes their **package-lock.json** and runs `npm install` again this won't cause any breakage to the users code (It will just result in all the files being present in node_modules)

**Comment by isaacs** [comment]
Summarizing objections raised in RFC meeting discussion:

First, `package-lock.json` is probably not the right place for something like this.  That file is ephemeral, and should really never be hand-edited.  The `package.json` and `.npmrc` files are the place to put user requests about dependencies and package installation behaviors.  This point is of course a bikeshed, and could be addressed in a number of perfectly reasonable ways.

More importantly, this feels like too much access to internal details of packages, which opens the door to some unfortunate effects.  If I run `npm install react --files umd/react.production.min.js`, then what happens when a dependency of mine requires a different file from react?  We could no longer dedupe as easily, or would have to end up ignoring the `--files` config in many cases.  Also, what happens if I do `npm install foo --files=lib/bar.js`, and then foo decides to move its internal module to `lib/bar/index.js`?  With this feature, _any_ changes to the internal structure of a package could potentially be a breaking change for downstream users.

Note that there is (or more accurately, _will be_) a way to address this using [overrides](https://github.com/npm/rfcs/pull/129).  You could create a package containing just the pieces of react that you know you need, and then add an override to your package.json:

```json
{
  "overrides": {
    "react@16": "@username/my-trimmed-down-react@16"
  }
}
```

That might of course break any of your dependencies that require more files, but you'll have an easy escape hatch:

```json
{
  "overrides": {
    "react@16": "npm:@username/my-trimmed-down-react@16",
    "dep-that-needs-real-react": {
      "react@16": "16"
    }
  }
}
```

Doing the feature as specced here, in a way that's safe for dependency deduplication, is a lot more complexity than it looks like, and could easily *increase* the size of packages stored on disk, rather than decrease it.

Another workaround I can think, which is not _exactly_ trivial or straightforward, but is available today, would be to use `bundleDependencies` and check in the version of react with the extra files removed.  Basically, you'd put this in your package.json file:

```json
{
  "dependencies": {
    "react": "16"
  },
  "bundleDependencies": [
    "react"
  ]
}
```

Then, put this in `node_modules/.gitignore`:

```
react/
!react/umd/react.production.min.js
```

Then, run:

```
git add node_modules/.gitignore node_modules/react/umd/react.production.min.js
git clean -fd node_modules/react
```

Anyone who checks out your project will get a bundled version of react with extra files stripped out, and you'll see it as a change when you upgrade react with npm.  If any meta-deps that depend on react break as a result, well, that's on you :joy:

Lastly, even more future roadmap ideas (that is to say, getting a little bit vapor-ware/science-fiction lol), to the extent that the core problem to be solved here is "I have too many copies of the same files (that I'm not even using) across dozens or hundreds of projects", the solution might be more adequately addressed using a virtual filesystem approach somewhat like tink or PnP.  We do plan to explore this in npm v8, and done right, you'd only ever download the files you actually load, and only one time per unique file hash, unless you explicitly opted in to unwinding the full `node_modules` dependency tree.

Since there are workarounds today, and better ones planned, and this opens the door to a handful of loaded footguns, we're not going to move forward on it.  Thanks for the suggestion, though, and I hope you stick around and share more ideas!

**Comment by Rafi993** [comment]
Thanks for your time @isaacs
