### ISSUE TITLE
[FEATURE] Full local caching to reduce global network workload

### ISSUE THREAD

**Issue by AaronNGray** [npm/rfcs#67]
# What / Why
For green environmental reasons like trying to help save the planet can we have local package caching builtin to NPM by default.

## When
by default when past an experimental feature.

## Where
local npm

### Current Behavior
limited caching

### Expected Behavior
full caching of all repositories initially using https://github.com/local-npm/local-npm before it becomes properly builtin for efficiency reasons.

## Who

n/a

## References

n/a

**Comment by isaacs** [comment]
> For green environmental reasons like trying to help save the planet can we have local package caching builtin to NPM by default.

Um... it is?

npm already caches every request, keyed by content-address, following the HTTP caching specification guidelines.  Check out https://github.com/npm/cacache https://github.com/npm/make-fetch-happen and https://github.com/npm/pacote

The benefit of using something like `local-npm` is that you can _share_ the caches between npm users on a given network (like, in an office or something).  But running `local-npm` on your machine and setting the registry to `localhost` will only serve to cache the same thing in two places.  Double the caching is not any fewer http requests, just more disk space ;)

The only situation in which this would result in fewer HTTP requests over the network would be if `local-npm` is violating the HTTP spec and caching (or failing to revalidate) when it ought to.  And we're not gonna do that, it's in the spec for a reason.

You can do `npm config set prefer-offline` if you wish to _always_ use the cached copy if it exists.  But that has to be an opt-in behavior, for (imo) obvious reasons.

It _would_ be interesting, and has been suggested in the past, to explore how we might use some kind of peer-to-peer network to share your `.npm/_cacache` folder between users.  Since cacache uses the content-address as a key, it's resilient against cache poisoning (ie, it treats an integrity mismatch as a cache miss, so `make-fetch-happen` just refetches that resource as if it wasn't in the cache).  But it's probably not a priority in the near future.

If you really wanna save the planet, don't delete your npm cache, and tell others to do the same!

**Comment by isaacs** [comment]
Also, if we're talking about _global_ network traffic, it's worth noting that the npm registry is already fronted by a globally distributed content delivery network.  So you're not typically fetching any further than the closest CDN point of presence, and we usually see a >99% cache hit rate.
