### ISSUE TITLE
Is there a migration guide for moving OpenLayers code under npm?

### ISSUE THREAD

**Issue by nufosmatic** [npm/rfcs#82]
I am not asking for a new document, just haven't found one, and the search is becoming frustrating.

We implemented an OpenLayers solution some years ago using ol2 (http://www.nufosmatic.com). The results were very satisfactory, and the new mapping capabilities allowed us to expand beyond what our circa 2004 primitive maps allowed.

However, like anything, ol2 will become stale and unusable. But, the leap to ol3+ is a big one, and some of the features of ol2 we settled upon are just simply not there.

We have found some ol3+ examples that seem to address our needs, but the v6.1.1 examples all seem to be abstracted to NPM. Now, we find some features of NPM very interesting (the development server/code and test process is really very nice), but there is this nasty bit of having to re-code all of the function names because of the NPM import process. OK, we've got a lot of re-coding to do anyway, and that's probably not no big a problem.

We have also found some third-party ol3+ examples that address missing features in ol2 that are NOT addressed in the ol3+ examples. However, bringing these examples under NPM has been most frustrating. It seems that eventually we get to "X is not a constructor" or "X is undefined" on examples that clearly work outside of NPM (especially when 'X' is something in ol3 that should be visible and correct).

Is there a doc that gives guidance on migrating a non-NPM ol3+ codebase under NPM?

**Comment by isaacs** [comment]
I'm sorry, I'm not familiar with OpenLayers.  But if your question is "how to get started using npm for dependencies", there are lots of words on the internet about that subject.  I'd suggest looking for some OpenLayer community resources that may discuss migration, as it sounds like the issue is more about migrating from ol2 to ol3 than anything specific to npm.

If there's a suggestion or request for comments regarding _npm itself_ that I'm missing, I'm happy to re-open this to discuss.

**Comment by nufosmatic** [comment]
Thank you. I appreciate an answer.
